30 Get Candle Letter Information API
2022Allie/ChocokCake_Backend pull request #39
Opened 2022-07-03 14:30 UTC by soyeonkim0227

2022-07-03 14:33 UTC, jeongjiwoo0522 requested changes

2022-07-03 14:33 UTC, jeongjiwoo0522 commented on src/main/java/com/example/chocokcake/controller/CandleController.java
> +    public LetterResponse getCandle(@PathVariable("cake_id") Long cake_id, @PathVariable("candle_id") Long candle_id) {
snake_case 말고 kamelCase

아름답지 않아요

2022-07-04 04:49 UTC, jeongjiwoo0522 commented
거기만 바꾸면 될까요

2022-07-04 13:43 UTC, gurdl0525 approved these changes

2022-07-04 13:44 UTC, gurdl0525 approved these changes

2022-07-04 13:44 UTC, merged